DGL backend not selected or invalid.  Assuming PyTorch for now.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/lib/condor/execute/dir_877837/PID_GNN/src/train_lightning1.py", line 224, in <module>
    main()
  File "/var/lib/condor/execute/dir_877837/PID_GNN/src/train_lightning1.py", line 167, in main
    trainer = L.Trainer(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 401, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 149, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 389, in _set_parallel_devices_and_init_accelerator
    self._devices_flag = accelerator_cls.parse_devices(self._devices_flag)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/accelerators/cuda.py", line 82, in parse_devices
    return _parse_gpu_ids(devices, include_cuda=True)
  File "/usr/local/lib/python3.8/dist-packages/lightning_fabric/utilities/device_parser.py", line 102, in _parse_gpu_ids
    return _sanitize_gpu_ids(gpus, include_cuda=include_cuda, include_mps=include_mps)
  File "/usr/local/lib/python3.8/dist-packages/lightning_fabric/utilities/device_parser.py", line 135, in _sanitize_gpu_ids
    raise MisconfigurationException(
lightning_fabric.utilities.exceptions.MisconfigurationException: You requested gpu: [1]
 But your machine only has: [0]
